---
name: Rails CI
on: [push]
env:
  RAILS_ENV: test
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
  yarn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: yarn
      - run: yarn install --immutable
  brakeman:
    runs-on: ubuntu-latest
    needs: bundle
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bin/brakeman
  rubocop:
    runs-on: ubuntu-latest
    needs: bundle
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bin/rubocop
  rspec:
    runs-on: ubuntu-latest
    needs:
      - bundle
      - yarn
    env:
      PGHOST: localhost
      PGUSER: kalmiya
      PGPASSWORD: kalmiya
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: kalmiya_test
          POSTGRES_PASSWORD: kalmiya
          POSTGRES_USER: kalmiya
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: yarn
      - run: yarn install --immutable
      - run: bin/rails db:setup
      - run: bin/rails assets:precompile
      - run: bin/rspec
      - uses: codecov/codecov-action@v4
